### ISSUE TITLE
how to set multiple administrators to a group?

### ISSUE THREAD

**Issue by felipemarciano** [perezdidac/WhatsAPINet#313]

**Comment by felipemarciano** [comment]
Por favor ajuda, eu preciso ter vários admin em um grupo.

Tks

**Comment by McBacker** [comment]
Hey, english, buddy!

**Comment by felipemarciano** [comment]
<i>WhatsApp.cs</i>
<b>Create new method</b>
<pre><code class='language-cs'>
public void SendPromoteParticipants(string gjid, IEnumerable<string> participants)
        {
            string id = TicketCounter.MakeId("promote_group_participants_");
            this.SendVerbParticipants(gjid, participants, id, "promote");
        }
</code></pre>
<b>Change "w:g" to "w:g2"</b>
<pre><code class='language-cs'>
protected void SendVerbParticipants(string gjid, IEnumerable<string> participants, string id, string inner_tag)
        {
IEnumerable<ProtocolTreeNode> source = from jid in participants select new ProtocolTreeNode("participant", new[] { new KeyValue("jid", GetJID(jid)) });
            var child = new ProtocolTreeNode(inner_tag, null, source);
            var node = new ProtocolTreeNode("iq", new[] { new KeyValue("id", id), new KeyValue("type", "set"), new KeyValue("xmlns", "w:g2"), new KeyValue("to", GetJID(gjid)) }, child);
            this.SendNode(node);
        }
</code></pre>
