### ISSUE TITLE
send image message does not work

### ISSUE THREAD

**Issue by diyaa-hamza** [perezdidac/WhatsAPINet#322]
Hello,

I tried to send an image to my number but it did not work!
1- convert image into byte array.
2- Create user using WhatsUserManager then the function CreateUser("xxxxxxxxx@s.whatsapp.net","name")
3- send the message using the function SendMessageImage()

why it did not work!

**Comment by diyaa-hamza** [comment]
it's work now I had mistake in the CreatUser funcation
it should be like this
CreateUser("number","name")
number with out @s.whatsapp.net

**Comment by brittson** [comment]
can you please post the code for image sending , thanks

**Comment by diyaa-hamza** [comment]
@brittson yeah sure below my VB code

    Dim usrMan As New WhatsUserManager()
            Dim tmpUser = usrMan.CreateUser("TargetNumber", "you have to create any name")
            wa.SendMessageImage(tmpUser.GetFullJid(), imgAsByteArray(), ApiBase.ImageType.PNG)

and you have to convert the image into byte Array (you can find many many code on google).
