### ISSUE TITLE
How to get message status (delivered or red)

### ISSUE THREAD

**Issue by diyaa-hamza** [perezdidac/WhatsAPINet#324]
Hello,

How can I get the message status that I sent it already?

Tnx

**Comment by felipemarciano** [comment]
Use OnGetMessageReceivedClient and OnGetMessageReceivedServer.

**Comment by diyaa-hamza** [comment]
@felipemarciano thank you it's work. but How can I get the status (Read or delivered).

**Comment by felipemarciano** [comment]
1 - OnGetMessageReceivedServer - delivered on server
2 - OnGetMessageReceivedClient - delivered on client
3 - OnGetMessageReceivedClient - Read

**Comment by diyaa-hamza** [comment]
@felipemarciano  it's working..tnx

**Comment by rajeevkk143** [comment]
hi,
can any one post the code with event for receiving message
