### ISSUE TITLE
New Message Encrypted

### ISSUE THREAD

**Issue by fuad86** [perezdidac/WhatsAPINet#329]
I have a problem with new message, WhatsAPINet can't read  for new user whatsapp.
For old whatsapp member, it is ok, run well.

This is the debug message :
RECVD : < message from="628531234444@s.whatsapp.net" id="1425099999-.-704" type=
"text" t="1425099977" notify="test ?">
RECVD :   < enc v="1" type="msg" av="Android/2.11.505">3
!?      ???7??S??S u_-W?O???s???
% "? ????gM?-+?e???/?</enc>
RECVD : </message>

The same error / issue , in :
https://github.com/mgp25/WhatsAPI-Official/issues/109
https://github.com/loqui/im/issues/598

**Comment by mgp25** [comment]
@fuad86 take the data from WhatsAPI Official, its already fixed.

**Comment by fuad86** [comment]
@mgp25 : thank you sir... ok.
But iam using WhatsAPINet, can you explain to me, how to solve it?
Thank You

**Comment by fuad86** [comment]
@mgp25 : ok sir..... thank you...
this is solved, i have foud your solution
