### ISSUE TITLE
Old versión on RequestCode

### ISSUE THREAD

**Issue by Xaamin** [perezdidac/WhatsAPINet#343]
When I try registering a new phone number I get failed response, reason old_version.
What is the whatsapp correct versión to replace current 2.11.272 ? And what will be the correct user agent versión ?
Thanks. Great API. Great job.

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPINet

**Comment by Xaamin** [comment]
Thanks Marcos.
